game: game.c board_generator.c dictionary.c score_board.c word_checker.c game_hash_table.c
	gcc -o boggle game.c board_generator.c dictionary.c score_board.c word_checker.c game_hash_table.c -I. -std=c99
